import { Injectable } from '@angular/core';
import { Pokeinfos } from './pokeinfos';

@Injectable({
  providedIn: 'root'
})
export class PokemonListService {

  pokemoninfos: Pokeinfos[] = [
    {
      "id": 1,
      "name": "Bulbasaur",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png",
      "description": "For some time after its birth, it uses the nutrients that are packed into the seed on its back in order to grow.",
      "height": 0.7,
      "weight": 6.9,
      "type": "Grass and Poison",
      "category": "Seed",
      "level": 1,
      "hp": 3,
      "attack": 3,
      "defense": 3,
      "sattack": 4,
      "sdefense": 4,
      "speed": 3,
      "abilities": "Overgrow",
      "descabil": "Powers up Grass-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Ice, Flying and Psychcic",
      "price": 50
    },
    {
      "id": 2,
      "name": "Ivysaur",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/002.png",
      "description": "The more sunlight Ivysaur bathes in, the more strength wells up within it, allowing the bud on its back to grow larger.",
      "height": 1,
      "weight": 13,
      "type": "Grass and Poison",
      "category": "Seed",
      "level": 2,
      "hp": 4,
      "attack": 4,
      "defense": 4,
      "sattack": 5,
      "sdefense": 5,
      "speed": 4,
      "abilities": "Overgrow",
      "descabil": "Powers up Grass-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Ice, Flying and Psychcic",
      "price": 100
    },
    {
      "id": 3,
      "name": "Venusaur",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/003.png",
      "description": "While it basks in the sun, it can convert the light into energy. As a result, it is more powerful in the summertime.",
      "height": 2,
      "weight": 100,
      "type": "Grass and Poison",
      "category": "Seed",
      "level": 3,
      "hp": 5,
      "attack": 5,
      "defense": 5,
      "sattack": 6,
      "sdefense": 6,
      "speed": 5,
      "abilities": "Overgrow",
      "descabil": "Powers up Grass-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Ice, Flying and Psychcic",
      "price": 150
    },
    {
      "id": 4,
      "name": "Charmander",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png",
      "description": "The flame on its tail shows the strength of its life-force. If Charmander is weak, the flame also burns weakly.",
      "height": 0.6,
      "weight": 8.5,
      "type": "Fire",
      "category": "Lizard",
      "level": 1,
      "hp": 3,
      "attack": 4,
      "defense": 3,
      "sattack": 4,
      "sdefense": 3,
      "speed": 4,
      "abilities": "Blaze",
      "descabil": "Powers up Fire-type moves when the Pokémon's HP is low.",
      "weaknesses": "Water, Ground and Rock",
      "price": 50
    },
    {
      "id": 5,
      "name": "Charmeleon",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/005.png",
      "description": "When it swings its burning tail, the temperature around it rises higher and higher, tormenting its opponents",
      "height": 1.1,
      "weight": 19,
      "type": "Fire",
      "category": "Flame",
      "level": 2,
      "hp": 4,
      "attack": 4,
      "defense": 4,
      "sattack": 5,
      "sdefense": 4,
      "speed": 5,
      "abilities": "Blaze",
      "descabil": "Powers up Fire-type moves when the Pokémon's HP is low.",
      "weaknesses": "Water, Ground and Rock",
      "price": 100
    },
    {
      "id": 6,
      "name": "Charizard",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/006.png",
      "description": "If Charizard becomes truly angered, the flame at the tip of its tail burns in a light blue shade.",
      "height": 1.7,
      "weight": 90.5,
      "type": "Fire and Flying",
      "category": "Flame",
      "level": 3,
      "hp": 5,
      "attack": 5,
      "defense": 5,
      "sattack": 7,
      "sdefense": 5,
      "speed": 6,
      "abilities": "Blaze",
      "descabil": "Powers up Fire-type moves when the Pokémon's HP is low.",
      "weaknesses": "Water, Eletric and Rock",
      "price": 150
    },
    {
      "id": 7,
      "name": "Squirtle",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/007.png",
      "description": "After birth, its back swells and hardens into a shell. It sprays a potent foam from its mouth.",
      "height": 0.5,
      "weight": 9,
      "type": "Water",
      "category": "Tiny Turtle",
      "level": 1,
      "hp": 3,
      "attack": 3,
      "defense": 4,
      "sattack": 3,
      "sdefense": 4,
      "speed": 3,
      "abilities": "Torrent",
      "descabil": "Powers up Water-type moves when the Pokémon's HP is low.",
      "weaknesses": "Grass and Eletric",
      "price": 50
    },
    {
      "id": 8,
      "name": "Wartortle",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/008.png",
      "description": "Wartortle's long, furry tail is a symbol of longevity, so this Pokémon is quite popular among older people.",
      "height": 1,
      "weight": 22.5,
      "type": "Water",
      "category": "Turtle",
      "level": 2,
      "hp": 4,
      "attack": 4,
      "defense": 5,
      "sattack": 4,
      "sdefense": 5,
      "speed": 4,
      "abilities": "Torrent",
      "descabil": "Powers up Water-type moves when the Pokémon's HP is low.",
      "weaknesses": "Grass and Eletric",
      "price": 100
    },
    {
      "id": 9,
      "name": "Blastoise",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/009.png",
      "description": "It deliberately increases its body weight so it can withstand the recoil of the water jets it fires.",
      "height": 1.6,
      "weight": 85.5,
      "type": "Water",
      "category": "Shellfish",
      "level": 3,
      "hp": 5,
      "attack": 5,
      "defense": 6,
      "sattack": 5,
      "sdefense": 7,
      "speed": 5,
      "abilities": "Torrent",
      "descabil": "Powers up Water-type moves when the Pokémon's HP is low.",
      "weaknesses": "Grass and Eletric",
      "price": 150
    },
    {
      "id": 10,
      "name": "Caterpie",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/010.png",
      "description": "For protection, it releases a horrible stench from the antenna on its head to drive away enemies.",
      "height": 0.3,
      "weight": 2.9,
      "type": "Bug",
      "category": "Worm",
      "level": 1,
      "hp": 3,
      "attack": 2,
      "defense": 3,
      "sattack": 2,
      "sdefense": 2,
      "speed": 3,
      "abilities": "Shield Dust",
      "descabil": "Protective dust shields the Pokémon from the additional effects of moves.",
      "weaknesses": "Fire, Flying and Rock",
      "price": 50
    },
    {
      "id": 11,
      "name": "Metapod",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/011.png",
      "description": "It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.",
      "height": 0.7,
      "weight": 9.9,
      "type": "Bug",
      "category": "Cocoon",
      "level": 2,
      "hp": 3,
      "attack": 2,
      "defense": 4,
      "sattack": 2,
      "sdefense": 2,
      "speed": 2,
      "abilities": "Shed Skin",
      "descabil": "The Pokémon may cure its own status conditions by shedding its skin.",
      "weaknesses": "Fire, Flying and Rock",
      "price": 100
    },
    {
      "id": 12,
      "name": "Butterfree",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/012.png",
      "description": "It loves the nectar of flowers and can locate flower patches that have even tiny amounts of pollen.",
      "height": 1.1,
      "weight": 32,
      "type": "Bug and Flying",
      "category": "Butterfly",
      "level": 3,
      "hp": 4,
      "attack": 3,
      "defense": 3,
      "sattack": 6,
      "sdefense": 5,
      "speed": 5,
      "abilities": "Compound Eyes",
      "descabil": "The Pokémon's compound eyes boost its accuracy.",
      "weaknesses": "Fire, Eletric, Ice, Flying and Rock",
      "price": 150
    },
    {
      "id": 13,
      "name": "Weedle",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/013.png",
      "description": "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.",
      "height": 0.3,
      "weight": 3.2,
      "type": "Bug and Poison",
      "category": "Hairy Bug",
      "level": 1,
      "hp": 3,
      "attack": 3,
      "defense": 2,
      "sattack": 2,
      "sdefense": 2,
      "speed": 3,
      "abilities": "Shield Dust",
      "descabil": "Protective dust shields the Pokémon from the additional effects of moves.",
      "weaknesses": "Fire, Flying, Psychic and Rock",
      "price": 50
    },
    {
      "id": 14,
      "name": "Kakuna",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/014.png",
      "description": "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.",
      "height": 0.6,
      "weight": 10,
      "type": "Bug and Poison",
      "category": "Cocoon",
      "level": 2,
      "hp": 3,
      "attack": 2,
      "defense": 3,
      "sattack": 2,
      "sdefense": 2,
      "speed": 3,
      "abilities": "Shed Skin",
      "descabil": "The Pokémon may cure its own status conditions by shedding its skin.",
      "weaknesses": "Fire, Flying, Psychic and Rock",
      "price": 100
    },
    {
      "id": 15,
      "name": "Beedrill",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/015.png",
      "description": "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
      "height": 1,
      "weight": 29.5,
      "type": "Bug and Poison",
      "category": "Poison Bee",
      "level": 3,
      "hp": 4,
      "attack": 6,
      "defense": 3,
      "sattack": 3,
      "sdefense": 5,
      "speed": 5,
      "abilities": "Swarm",
      "descabil": "Powers up Bug-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Flying, Psychic and Rock",
      "price": 150
    },
    {
      "id": 16,
      "name": "Pidgey",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/016.png",
      "description": "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.",
      "height": 0.3,
      "weight": 1.8,
      "type": "Normal and Flying",
      "category": "Tiny Bird",
      "level": 1,
      "hp": 3,
      "attack": 3,
      "defense": 3,
      "sattack": 3,
      "sdefense": 3,
      "speed": 4,
      "abilities": "Keen Eye",
      "descabil": "The Pokémon's keen eyes prevent its accuracy from being lowered.",
      "weaknesses": "Eletric, Ice and Rock",
      "price": 50
    },
    {
      "id": 17,
      "name": "Pidgeotto",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/017.png",
      "description": "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.",
      "height": 1.1,
      "weight": 30,
      "type": "Normal and Flying",
      "category": "Bird",
      "level": 2,
      "hp": 4,
      "attack": 4,
      "defense": 4,
      "sattack": 3,
      "sdefense": 3,
      "speed": 5,
      "abilities": "Keen Eye",
      "descabil": "The Pokémon's keen eyes prevent its accuracy from being lowered.",
      "weaknesses": "Eletric, Ice and Rock",
      "price": 100
    },
    {
      "id": 18,
      "name": "Pidgeot",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/018.png",
      "description": "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.",
      "height": 1.5,
      "weight": 39.5,
      "type": "Normal and Flying",
      "category": "Bird",
      "level": 3,
      "hp": 5,
      "attack": 5,
      "defense": 5,
      "sattack": 5,
      "sdefense": 5,
      "speed": 6,
      "abilities": "Tangled Feet",
      "descabil": "Boosts the Pokémon's evasiveness if it is confused.",
      "weaknesses": "Eletric, Ice and Rock",
      "price": 150
    },
    {
      "id": 19,
      "name": "Rattata",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/019.png",
      "description": "Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.",
      "height": 0.3,
      "weight": 3.5,
      "type": "Normal",
      "category": "Mouse",
      "level": 1,
      "hp": 2,
      "attack": 4,
      "defense": 3,
      "sattack": 2,
      "sdefense": 3,
      "speed": 5,
      "abilities": "Run Away",
      "descabil": "Enables a sure getaway from wild Pokémon.",
      "weaknesses": "Fighting",
      "price": 50
    },
    {
      "id": 20,
      "name": "Raticate",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/020.png",
      "description": "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.",
      "height": 0.7,
      "weight": 18.5,
      "type": "Normal",
      "category": "Mouse",
      "level": 2,
      "hp": 4,
      "attack": 5,
      "defense": 4,
      "sattack": 3,
      "sdefense": 5,
      "speed": 6,
      "abilities": "Guts",
      "descabil": "It's so gutsy that having a status condition boosts the Pokémon's Attack stat.",
      "weaknesses": "Fighting",
      "price": 100
    },
    {
      "id": 21,
      "name": "Spearow",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/021.png",
      "description": "Inept at flying high. However, it can fly around very fast to protect its territory.",
      "height": 0.3,
      "weight": 2,
      "type": "Normal and Flying",
      "category": "Tiny Bird",
      "level": 1,
      "hp": 3,
      "attack": 4,
      "defense": 2,
      "sattack": 2,
      "sdefense": 2,
      "speed": 5,
      "abilities": "Keen Eye",
      "descabil": "The Pokémon's keen eyes prevent its accuracy from being lowered.",
      "weaknesses": "Eletric, Ice and Rock",
      "price": 50
    },
    {
      "id": 22,
      "name": "Fearow",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/022.png",
      "description": "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.",
      "height": 1.2,
      "weight": 38,
      "type": "Normal and Flying",
      "category": "Beak",
      "level": 2,
      "hp": 4,
      "attack": 6,
      "defense": 4,
      "sattack": 4,
      "sdefense": 4,
      "speed": 6,
      "abilities": "Keen Eye",
      "descabil": "The Pokémon's keen eyes prevent its accuracy from being lowered.",
      "weaknesses": "Eletric, Ice and Rock",
      "price": 100
    },
    {
      "id": 23,
      "name": "Ekans",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/023.png",
      "description": "It can freely detach its jaw to swallow large prey whole. It can become too heavy to move, however.",
      "height": 2,
      "weight": 6.9,
      "type": "Poison",
      "category": "Snake",
      "level": 1,
      "hp": 3,
      "attack": 4,
      "defense": 3,
      "sattack": 3,
      "sdefense": 4,
      "speed": 4,
      "abilities": "Shed Skin",
      "descabil": "The Pokémon may cure its own status conditions by shedding its skin.",
      "weaknesses": "Ground and Psychic",
      "price": 50
    },
    {
      "id": 24,
      "name": "Arbok",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/024.png",
      "description": "The pattern on its belly appears to be a frightening face. Weak foes will flee just at the sight of the pattern.",
      "height": 3.5,
      "weight": 65,
      "type": "Poison",
      "category": "Snake",
      "level": 2,
      "hp": 4,
      "attack": 6,
      "defense": 5,
      "sattack": 4,
      "sdefense": 5,
      "speed": 5,
      "abilities": "Intimidate",
      "descabil": "When the Pokémon enters a battle, it intimidates opposing Pokémon and makes them cower, lowering their Attack stats.",
      "weaknesses": "Ground and Psychic",
      "price": 100
    },
    {
      "id": 25,
      "name": "Pichu",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/172.png",
      "description": "It is unskilled at storing electric power. Any kind of shock causes it to discharge energy spontaneously..",
      "height": 0.3,
      "weight": 2,
      "type": "Eletric",
      "category": "Tiny Mouse",
      "level": 1,
      "hp": 2,
      "attack": 3,
      "defense": 1,
      "sattack": 3,
      "sdefense": 3,
      "speed": 4,
      "abilities": "Static",
      "descabil": "The Pokémon is charged with static electricity and may paralyze attackers that make direct contact with it.",
      "weaknesses": "Ground",
      "price": 50
    },
    {
      "id": 26,
      "name": "Pikachu",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/025.png",
      "description": "When it is angered, it immediately discharges the energy stored in the pouches in its cheeks.",
      "height": 0.4,
      "weight": 6,
      "type": "Eletric",
      "category": "Mouse",
      "level": 2,
      "hp": 3,
      "attack": 4,
      "defense": 3,
      "sattack": 3,
      "sdefense": 3,
      "speed": 6,
      "abilities": "Static",
      "descabil": "The Pokémon is charged with static electricity and may paralyze attackers that make direct contact with it.",
      "weaknesses": "Ground",
      "price": 100
    },
    {
      "id": 27,
      "name": "Raichu",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/026.png",
      "description": "Its tail discharges electricity into the ground, protecting it from getting shocked.",
      "height": 0.8,
      "weight": 30,
      "type": "Eletric",
      "category": "Mouse",
      "level": 3,
      "hp": 4,
      "attack": 6,
      "defense": 4,
      "sattack": 6,
      "sdefense": 5,
      "speed": 7,
      "abilities": "Static",
      "descabil": "The Pokémon is charged with static electricity and may paralyze attackers that make direct contact with it.",
      "weaknesses": "Ground",
      "price": 150
    },
    {
      "id": 28,
      "name": "Dratini",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/147.png",
      "description": "It sheds many layers of skin as it grows larger. During this process, it is protected by a rapid waterfall.",
      "height": 1.8,
      "weight": 3.3,
      "type": "Dragon",
      "category": "Dragon",
      "level": 1,
      "hp": 3,
      "attack": 4,
      "defense": 3,
      "sattack": 3,
      "sdefense": 3,
      "speed": 3,
      "abilities": "Shed Skin",
      "descabil": "The Pokémon may cure its own status conditions by shedding its skin.",
      "weaknesses": "Ice, Dragon and Fairy",
      "price": 50
    },
    {
      "id": 29,
      "name": "Dragonair",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/148.png",
      "description": "They say that if it emits an aura from its whole body, the weather will begin to change instantly.",
      "height": 4,
      "weight": 16.5,
      "type": "Dragon",
      "category": "Dragon",
      "level": 2,
      "hp": 4,
      "attack": 5,
      "defense": 4,
      "sattack": 5,
      "sdefense": 5,
      "speed": 5,
      "abilities": "Shed Skin",
      "descabil": "The Pokémon may cure its own status conditions by shedding its skin.",
      "weaknesses": "Ice, Dragon and Fairy",
      "price": 100
    },
    {
      "id": 30,
      "name": "Dragonite",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/149.png",
      "description": "It is said that somewhere in the ocean lies an island where these gather. Only they live there.",
      "height": 2.2,
      "weight": 210,
      "type": "Dragon and Flying",
      "category": "Dragon",
      "level": 3,
      "hp": 6,
      "attack": 8,
      "defense": 6,
      "sattack": 6,
      "sdefense": 6,
      "speed": 5,
      "abilities": "Inner Focus",
      "descabil": "The Pokémon's intense focus prevents it from flinching or being affected by Intimidate.",
      "weaknesses": "Ice, Rock, Dragon and Fairy",
      "price": 150
    },
    {
      "id": 31,
      "name": "Abra",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/063.png",
      "description": "This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields.",
      "height": 0.9,
      "weight": 19.5,
      "type": "Psychic",
      "category": "Psi",
      "level": 1,
      "hp": 2,
      "attack": 2,
      "defense": 1,
      "sattack": 7,
      "sdefense": 4,
      "speed": 6,
      "abilities": "Inner Focus",
      "descabil": "The Pokémon's intense focus prevents it from flinching or being affected by Intimidate.",
      "weaknesses": "Bug, Ghost and Dark",
      "price": 50
    },
    {
      "id": 32,
      "name": "Kadabra",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/064.png",
      "description": "Using its psychic power, Kadabra levitates as it sleeps. It uses its springy tail as a pillow.",
      "height": 1.3,
      "weight": 56.5,
      "type": "Psychic",
      "category": "Psi",
      "level": 2,
      "hp": 3,
      "attack": 3,
      "defense": 2,
      "sattack": 8,
      "sdefense": 5,
      "speed": 7,
      "abilities": "Inner Focus",
      "descabil": "The Pokémon's intense focus prevents it from flinching or being affected by Intimidate.",
      "weaknesses": "Bug, Ghost and Dark",
      "price": 100
    },
    {
      "id": 33,
      "name": "Alakazam",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/065.png",
      "description": "It has an incredibly high level of intelligence. Some say that Alakazam remembers everything that ever happens to it, from birth till death.",
      "height": 1.5,
      "weight": 48,
      "type": "Psychic",
      "category": "Psi",
      "level": 3,
      "hp": 4,
      "attack": 3,
      "defense": 3,
      "sattack": 8,
      "sdefense": 6,
      "speed": 8,
      "abilities": "Synchronize",
      "descabil": "If the Pokémon is burned, paralyzed, or poisoned by another Pokémon, that Pokémon will be inflicted with the same status condition.",
      "weaknesses": "Bug, Ghost and Dark",
      "price": 150
    },
    {
      "id": 34,
      "name": "Chikorita",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/152.png",
      "description": "It loves to bask in the sunlight. It uses the leaf on its head to seek out warm places.",
      "height": 0.9,
      "weight": 6.4,
      "type": "Grass",
      "category": "Leaf",
      "level": 1,
      "hp": 3,
      "attack": 3,
      "defense": 4,
      "sattack": 3,
      "sdefense": 4,
      "speed": 3,
      "abilities": "Overgrow",
      "descabil": "Powers up Grass-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Ice, Poison, Flying and Bug",
      "price": 50
    },
    {
      "id": 35,
      "name": "Bayleef",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/153.png",
      "description": "The spicy scent that wafts from around Bayleef's neck somehow makes those who smell it want to fight.",
      "height": 1.2,
      "weight": 15.8,
      "type": "Grass",
      "category": "Leaf",
      "level": 2,
      "hp": 4,
      "attack": 4,
      "defense": 5,
      "sattack": 4,
      "sdefense": 5,
      "speed": 4,
      "abilities": "Overgrow",
      "descabil": "Powers up Grass-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Ice, Poison, Flying and Bug",
      "price": 100
    },
    {
      "id": 36,
      "name": "Meganium",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/154.png",
      "description": "Anyone who stands beside it becomes refreshed, just as if they were soaking in the soothing atmosphere of a forest.",
      "height": 1.8,
      "weight": 100.5,
      "type": "Grass",
      "category": "Herb",
      "level": 3,
      "hp": 5,
      "attack": 5,
      "defense": 6,
      "sattack": 5,
      "sdefense": 6,
      "speed": 5,
      "abilities": "Overgrow",
      "descabil": "Powers up Grass-type moves when the Pokémon's HP is low.",
      "weaknesses": "Fire, Ice, Poison, Flying and Bug",
      "price": 150
    },
    {
      "id": 37,
      "name": "Psyduck",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/054.png",
      "description": "It is constantly wracked by a headache. When the headache turns intense, it begins using mysterious powers.",
      "height": 0.8,
      "weight": 19.6,
      "type": "Water",
      "category": "Duck",
      "level": 2,
      "hp": 3,
      "attack": 4,
      "defense": 3,
      "sattack": 4,
      "sdefense": 3,
      "speed": 4,
      "abilities": "Cloud Nine",
      "descabil": "Eliminates the effects of weather.",
      "weaknesses": "Grass and Eletric",
      "price": 100
    },
    {
      "id": 38,
      "name": "Golduck",
      "pic": "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/055.png",
      "description": "When it swims at full speed using its long, webbed limbs, its forehead somehow begins to glow..",
      "height": 1.7,
      "weight": 76.6,
      "type": "Water",
      "category": "Duck",
      "level": 3,
      "hp": 5,
      "attack": 5,
      "defense": 5,
      "sattack": 6,
      "sdefense": 5,
      "speed": 5,
      "abilities": "Damp",
      "descabil": "The Pokémon dampens its surroundings, preventing all Pokémon from using explosive moves such as Self-Destruct.",
      "weaknesses": "Grass and Eletric",
      "price": 150
    }
  ];

  getAllPokemons(): Pokeinfos[] {
    return this.pokemoninfos;
  }

  getPokemonById(id: number): Pokeinfos | undefined {
    return this.pokemoninfos.find((pokemonList) => pokemonList.id === id)
  }

}
